version: '3.8'
services:
  web:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
      - /Users/sraga/Documents/TQE/assets:/app/src/assets
      - /app/src/assets/images/headshots
      - /app/src/assets/cricket
    command: ng serve --host 0.0.0.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # command: tail -f /dev/null

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /Users/sraga/Documents/TQE/assets/images/headshots:/usr/share/nginx/html/assets/images/headshots
      - /Users/sraga/Documents/TQE/assets/cricket:/usr/share/nginx/html/assets/cricket
    ports:
      - "80:80"
    depends_on:
      - web
    logging:
      driver: "none"
